// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: camel-agvs-communication.proto

#include "camel-agvs-communication.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_camel_2dagvs_2dcommunication_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_AgvInAgvs_camel_2dagvs_2dcommunication_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_camel_2dagvs_2dcommunication_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_CamelMessage_AllowFromAgvs_camel_2dagvs_2dcommunication_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_camel_2dagvs_2dcommunication_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_CamelMessage_ReportToAgvs_camel_2dagvs_2dcommunication_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_camel_2dagvs_2dcommunication_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Device_camel_2dagvs_2dcommunication_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_camel_2dagvs_2dcommunication_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Posion_camel_2dagvs_2dcommunication_2eproto;
namespace serialization {
class CamelMessage_AllowFromAgvsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CamelMessage_AllowFromAgvs> _instance;
} _CamelMessage_AllowFromAgvs_default_instance_;
class CamelMessage_ReportToAgvsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CamelMessage_ReportToAgvs> _instance;
} _CamelMessage_ReportToAgvs_default_instance_;
class CamelMessageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CamelMessage> _instance;
  const ::serialization::CamelMessage_AllowFromAgvs* allowfromagvs_;
  const ::serialization::CamelMessage_ReportToAgvs* reporttoagvs_;
} _CamelMessage_default_instance_;
class PosionDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Posion> _instance;
} _Posion_default_instance_;
class DeviceDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Device> _instance;
} _Device_default_instance_;
class AgvInAgvsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<AgvInAgvs> _instance;
} _AgvInAgvs_default_instance_;
}  // namespace serialization
static void InitDefaultsscc_info_AgvInAgvs_camel_2dagvs_2dcommunication_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::serialization::_AgvInAgvs_default_instance_;
    new (ptr) ::serialization::AgvInAgvs();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::serialization::AgvInAgvs::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_AgvInAgvs_camel_2dagvs_2dcommunication_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_AgvInAgvs_camel_2dagvs_2dcommunication_2eproto}, {}};

static void InitDefaultsscc_info_CamelMessage_camel_2dagvs_2dcommunication_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::serialization::_CamelMessage_default_instance_;
    new (ptr) ::serialization::CamelMessage();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::serialization::CamelMessage::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_CamelMessage_camel_2dagvs_2dcommunication_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_CamelMessage_camel_2dagvs_2dcommunication_2eproto}, {
      &scc_info_CamelMessage_AllowFromAgvs_camel_2dagvs_2dcommunication_2eproto.base,
      &scc_info_CamelMessage_ReportToAgvs_camel_2dagvs_2dcommunication_2eproto.base,}};

static void InitDefaultsscc_info_CamelMessage_AllowFromAgvs_camel_2dagvs_2dcommunication_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::serialization::_CamelMessage_AllowFromAgvs_default_instance_;
    new (ptr) ::serialization::CamelMessage_AllowFromAgvs();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::serialization::CamelMessage_AllowFromAgvs::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_CamelMessage_AllowFromAgvs_camel_2dagvs_2dcommunication_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_CamelMessage_AllowFromAgvs_camel_2dagvs_2dcommunication_2eproto}, {
      &scc_info_AgvInAgvs_camel_2dagvs_2dcommunication_2eproto.base,}};

static void InitDefaultsscc_info_CamelMessage_ReportToAgvs_camel_2dagvs_2dcommunication_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::serialization::_CamelMessage_ReportToAgvs_default_instance_;
    new (ptr) ::serialization::CamelMessage_ReportToAgvs();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::serialization::CamelMessage_ReportToAgvs::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_CamelMessage_ReportToAgvs_camel_2dagvs_2dcommunication_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_CamelMessage_ReportToAgvs_camel_2dagvs_2dcommunication_2eproto}, {
      &scc_info_Device_camel_2dagvs_2dcommunication_2eproto.base,
      &scc_info_Posion_camel_2dagvs_2dcommunication_2eproto.base,}};

static void InitDefaultsscc_info_Device_camel_2dagvs_2dcommunication_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::serialization::_Device_default_instance_;
    new (ptr) ::serialization::Device();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::serialization::Device::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Device_camel_2dagvs_2dcommunication_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Device_camel_2dagvs_2dcommunication_2eproto}, {}};

static void InitDefaultsscc_info_Posion_camel_2dagvs_2dcommunication_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::serialization::_Posion_default_instance_;
    new (ptr) ::serialization::Posion();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::serialization::Posion::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Posion_camel_2dagvs_2dcommunication_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Posion_camel_2dagvs_2dcommunication_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_camel_2dagvs_2dcommunication_2eproto[6];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_camel_2dagvs_2dcommunication_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_camel_2dagvs_2dcommunication_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_camel_2dagvs_2dcommunication_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::serialization::CamelMessage_AllowFromAgvs, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::serialization::CamelMessage_AllowFromAgvs, agv_),
  PROTOBUF_FIELD_OFFSET(::serialization::CamelMessage_AllowFromAgvs, errormessage_),
  PROTOBUF_FIELD_OFFSET(::serialization::CamelMessage_AllowFromAgvs, allowcharging_),
  PROTOBUF_FIELD_OFFSET(::serialization::CamelMessage_AllowFromAgvs, otheragv_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::serialization::CamelMessage_ReportToAgvs, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::serialization::CamelMessage_ReportToAgvs, currentstation_),
  PROTOBUF_FIELD_OFFSET(::serialization::CamelMessage_ReportToAgvs, version_),
  PROTOBUF_FIELD_OFFSET(::serialization::CamelMessage_ReportToAgvs, battery_),
  PROTOBUF_FIELD_OFFSET(::serialization::CamelMessage_ReportToAgvs, ischarging_),
  PROTOBUF_FIELD_OFFSET(::serialization::CamelMessage_ReportToAgvs, devices_),
  PROTOBUF_FIELD_OFFSET(::serialization::CamelMessage_ReportToAgvs, posion_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::serialization::CamelMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::serialization::CamelMessage, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  offsetof(::serialization::CamelMessageDefaultTypeInternal, allowfromagvs_),
  offsetof(::serialization::CamelMessageDefaultTypeInternal, reporttoagvs_),
  PROTOBUF_FIELD_OFFSET(::serialization::CamelMessage, onlyone_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::serialization::Posion, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::serialization::Posion, x_),
  PROTOBUF_FIELD_OFFSET(::serialization::Posion, y_),
  PROTOBUF_FIELD_OFFSET(::serialization::Posion, theta_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::serialization::Device, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::serialization::Device, id_),
  PROTOBUF_FIELD_OFFSET(::serialization::Device, name_),
  PROTOBUF_FIELD_OFFSET(::serialization::Device, value_),
  PROTOBUF_FIELD_OFFSET(::serialization::Device, isactivate_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::serialization::AgvInAgvs, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::serialization::AgvInAgvs, name_),
  PROTOBUF_FIELD_OFFSET(::serialization::AgvInAgvs, currentstation_),
  PROTOBUF_FIELD_OFFSET(::serialization::AgvInAgvs, targetstation_),
  PROTOBUF_FIELD_OFFSET(::serialization::AgvInAgvs, isuseable_),
  PROTOBUF_FIELD_OFFSET(::serialization::AgvInAgvs, hastask_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::serialization::CamelMessage_AllowFromAgvs)},
  { 9, -1, sizeof(::serialization::CamelMessage_ReportToAgvs)},
  { 20, -1, sizeof(::serialization::CamelMessage)},
  { 28, -1, sizeof(::serialization::Posion)},
  { 36, -1, sizeof(::serialization::Device)},
  { 45, -1, sizeof(::serialization::AgvInAgvs)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::serialization::_CamelMessage_AllowFromAgvs_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::serialization::_CamelMessage_ReportToAgvs_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::serialization::_CamelMessage_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::serialization::_Posion_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::serialization::_Device_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::serialization::_AgvInAgvs_default_instance_),
};

const char descriptor_table_protodef_camel_2dagvs_2dcommunication_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\036camel-agvs-communication.proto\022\rserial"
  "ization\"\337\003\n\014CamelMessage\022B\n\rallowFromAgv"
  "s\030\001 \001(\0132).serialization.CamelMessage.All"
  "owFromAgvsH\000\022@\n\014reportToAgvs\030\002 \001(\0132(.ser"
  "ialization.CamelMessage.ReportToAgvsH\000\032\217"
  "\001\n\rAllowFromAgvs\022%\n\003agv\030\001 \001(\0132\030.serializ"
  "ation.AgvInAgvs\022\024\n\014errorMessage\030\002 \001(\014\022\025\n"
  "\rallowCharging\030\003 \001(\010\022*\n\010otherAgv\030\004 \003(\0132\030"
  ".serialization.AgvInAgvs\032\253\001\n\014ReportToAgv"
  "s\022\026\n\016currentStation\030\001 \001(\014\022\017\n\007version\030\002 \001"
  "(\014\022\017\n\007battery\030\003 \001(\002\022\022\n\nisCharging\030\004 \001(\010\022"
  "&\n\007devices\030\005 \003(\0132\025.serialization.Device\022"
  "%\n\006posion\030\006 \001(\0132\025.serialization.PosionB\t"
  "\n\007onlyone\"-\n\006Posion\022\t\n\001X\030\001 \001(\002\022\t\n\001Y\030\002 \001("
  "\002\022\r\n\005Theta\030\003 \001(\002\"E\n\006Device\022\n\n\002id\030\001 \001(\005\022\014"
  "\n\004name\030\002 \001(\014\022\r\n\005value\030\004 \001(\002\022\022\n\nisActivat"
  "e\030\003 \001(\010\"l\n\tAgvInAgvs\022\014\n\004name\030\001 \001(\014\022\026\n\016cu"
  "rrentStation\030\002 \001(\014\022\025\n\rtargetStation\030\003 \001("
  "\014\022\021\n\tisUseable\030\004 \001(\010\022\017\n\007hasTask\030\005 \001(\010b\006p"
  "roto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_camel_2dagvs_2dcommunication_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_camel_2dagvs_2dcommunication_2eproto_sccs[6] = {
  &scc_info_AgvInAgvs_camel_2dagvs_2dcommunication_2eproto.base,
  &scc_info_CamelMessage_camel_2dagvs_2dcommunication_2eproto.base,
  &scc_info_CamelMessage_AllowFromAgvs_camel_2dagvs_2dcommunication_2eproto.base,
  &scc_info_CamelMessage_ReportToAgvs_camel_2dagvs_2dcommunication_2eproto.base,
  &scc_info_Device_camel_2dagvs_2dcommunication_2eproto.base,
  &scc_info_Posion_camel_2dagvs_2dcommunication_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_camel_2dagvs_2dcommunication_2eproto_once;
static bool descriptor_table_camel_2dagvs_2dcommunication_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_camel_2dagvs_2dcommunication_2eproto = {
  &descriptor_table_camel_2dagvs_2dcommunication_2eproto_initialized, descriptor_table_protodef_camel_2dagvs_2dcommunication_2eproto, "camel-agvs-communication.proto", 765,
  &descriptor_table_camel_2dagvs_2dcommunication_2eproto_once, descriptor_table_camel_2dagvs_2dcommunication_2eproto_sccs, descriptor_table_camel_2dagvs_2dcommunication_2eproto_deps, 6, 0,
  schemas, file_default_instances, TableStruct_camel_2dagvs_2dcommunication_2eproto::offsets,
  file_level_metadata_camel_2dagvs_2dcommunication_2eproto, 6, file_level_enum_descriptors_camel_2dagvs_2dcommunication_2eproto, file_level_service_descriptors_camel_2dagvs_2dcommunication_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_camel_2dagvs_2dcommunication_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_camel_2dagvs_2dcommunication_2eproto), true);
namespace serialization {

// ===================================================================

void CamelMessage_AllowFromAgvs::InitAsDefaultInstance() {
  ::serialization::_CamelMessage_AllowFromAgvs_default_instance_._instance.get_mutable()->agv_ = const_cast< ::serialization::AgvInAgvs*>(
      ::serialization::AgvInAgvs::internal_default_instance());
}
class CamelMessage_AllowFromAgvs::_Internal {
 public:
  static const ::serialization::AgvInAgvs& agv(const CamelMessage_AllowFromAgvs* msg);
};

const ::serialization::AgvInAgvs&
CamelMessage_AllowFromAgvs::_Internal::agv(const CamelMessage_AllowFromAgvs* msg) {
  return *msg->agv_;
}
CamelMessage_AllowFromAgvs::CamelMessage_AllowFromAgvs()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:serialization.CamelMessage.AllowFromAgvs)
}
CamelMessage_AllowFromAgvs::CamelMessage_AllowFromAgvs(const CamelMessage_AllowFromAgvs& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      otheragv_(from.otheragv_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  errormessage_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_errormessage().empty()) {
    errormessage_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.errormessage_);
  }
  if (from._internal_has_agv()) {
    agv_ = new ::serialization::AgvInAgvs(*from.agv_);
  } else {
    agv_ = nullptr;
  }
  allowcharging_ = from.allowcharging_;
  // @@protoc_insertion_point(copy_constructor:serialization.CamelMessage.AllowFromAgvs)
}

void CamelMessage_AllowFromAgvs::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_CamelMessage_AllowFromAgvs_camel_2dagvs_2dcommunication_2eproto.base);
  errormessage_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&agv_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&allowcharging_) -
      reinterpret_cast<char*>(&agv_)) + sizeof(allowcharging_));
}

CamelMessage_AllowFromAgvs::~CamelMessage_AllowFromAgvs() {
  // @@protoc_insertion_point(destructor:serialization.CamelMessage.AllowFromAgvs)
  SharedDtor();
}

void CamelMessage_AllowFromAgvs::SharedDtor() {
  errormessage_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete agv_;
}

void CamelMessage_AllowFromAgvs::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CamelMessage_AllowFromAgvs& CamelMessage_AllowFromAgvs::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CamelMessage_AllowFromAgvs_camel_2dagvs_2dcommunication_2eproto.base);
  return *internal_default_instance();
}


void CamelMessage_AllowFromAgvs::Clear() {
// @@protoc_insertion_point(message_clear_start:serialization.CamelMessage.AllowFromAgvs)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  otheragv_.Clear();
  errormessage_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == nullptr && agv_ != nullptr) {
    delete agv_;
  }
  agv_ = nullptr;
  allowcharging_ = false;
  _internal_metadata_.Clear();
}

const char* CamelMessage_AllowFromAgvs::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .serialization.AgvInAgvs agv = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_agv(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes errorMessage = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_errormessage();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool allowCharging = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          allowcharging_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .serialization.AgvInAgvs otherAgv = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_otheragv(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CamelMessage_AllowFromAgvs::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:serialization.CamelMessage.AllowFromAgvs)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .serialization.AgvInAgvs agv = 1;
  if (this->has_agv()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::agv(this), target, stream);
  }

  // bytes errorMessage = 2;
  if (this->errormessage().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_errormessage(), target);
  }

  // bool allowCharging = 3;
  if (this->allowcharging() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_allowcharging(), target);
  }

  // repeated .serialization.AgvInAgvs otherAgv = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_otheragv_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_otheragv(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:serialization.CamelMessage.AllowFromAgvs)
  return target;
}

size_t CamelMessage_AllowFromAgvs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:serialization.CamelMessage.AllowFromAgvs)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .serialization.AgvInAgvs otherAgv = 4;
  total_size += 1UL * this->_internal_otheragv_size();
  for (const auto& msg : this->otheragv_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // bytes errorMessage = 2;
  if (this->errormessage().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_errormessage());
  }

  // .serialization.AgvInAgvs agv = 1;
  if (this->has_agv()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *agv_);
  }

  // bool allowCharging = 3;
  if (this->allowcharging() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CamelMessage_AllowFromAgvs::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:serialization.CamelMessage.AllowFromAgvs)
  GOOGLE_DCHECK_NE(&from, this);
  const CamelMessage_AllowFromAgvs* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CamelMessage_AllowFromAgvs>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:serialization.CamelMessage.AllowFromAgvs)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:serialization.CamelMessage.AllowFromAgvs)
    MergeFrom(*source);
  }
}

void CamelMessage_AllowFromAgvs::MergeFrom(const CamelMessage_AllowFromAgvs& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:serialization.CamelMessage.AllowFromAgvs)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  otheragv_.MergeFrom(from.otheragv_);
  if (from.errormessage().size() > 0) {

    errormessage_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.errormessage_);
  }
  if (from.has_agv()) {
    _internal_mutable_agv()->::serialization::AgvInAgvs::MergeFrom(from._internal_agv());
  }
  if (from.allowcharging() != 0) {
    _internal_set_allowcharging(from._internal_allowcharging());
  }
}

void CamelMessage_AllowFromAgvs::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:serialization.CamelMessage.AllowFromAgvs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CamelMessage_AllowFromAgvs::CopyFrom(const CamelMessage_AllowFromAgvs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:serialization.CamelMessage.AllowFromAgvs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CamelMessage_AllowFromAgvs::IsInitialized() const {
  return true;
}

void CamelMessage_AllowFromAgvs::InternalSwap(CamelMessage_AllowFromAgvs* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  otheragv_.InternalSwap(&other->otheragv_);
  errormessage_.Swap(&other->errormessage_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(agv_, other->agv_);
  swap(allowcharging_, other->allowcharging_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CamelMessage_AllowFromAgvs::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void CamelMessage_ReportToAgvs::InitAsDefaultInstance() {
  ::serialization::_CamelMessage_ReportToAgvs_default_instance_._instance.get_mutable()->posion_ = const_cast< ::serialization::Posion*>(
      ::serialization::Posion::internal_default_instance());
}
class CamelMessage_ReportToAgvs::_Internal {
 public:
  static const ::serialization::Posion& posion(const CamelMessage_ReportToAgvs* msg);
};

const ::serialization::Posion&
CamelMessage_ReportToAgvs::_Internal::posion(const CamelMessage_ReportToAgvs* msg) {
  return *msg->posion_;
}
CamelMessage_ReportToAgvs::CamelMessage_ReportToAgvs()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:serialization.CamelMessage.ReportToAgvs)
}
CamelMessage_ReportToAgvs::CamelMessage_ReportToAgvs(const CamelMessage_ReportToAgvs& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      devices_(from.devices_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  currentstation_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_currentstation().empty()) {
    currentstation_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.currentstation_);
  }
  version_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_version().empty()) {
    version_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.version_);
  }
  if (from._internal_has_posion()) {
    posion_ = new ::serialization::Posion(*from.posion_);
  } else {
    posion_ = nullptr;
  }
  ::memcpy(&battery_, &from.battery_,
    static_cast<size_t>(reinterpret_cast<char*>(&ischarging_) -
    reinterpret_cast<char*>(&battery_)) + sizeof(ischarging_));
  // @@protoc_insertion_point(copy_constructor:serialization.CamelMessage.ReportToAgvs)
}

void CamelMessage_ReportToAgvs::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_CamelMessage_ReportToAgvs_camel_2dagvs_2dcommunication_2eproto.base);
  currentstation_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  version_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&posion_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ischarging_) -
      reinterpret_cast<char*>(&posion_)) + sizeof(ischarging_));
}

CamelMessage_ReportToAgvs::~CamelMessage_ReportToAgvs() {
  // @@protoc_insertion_point(destructor:serialization.CamelMessage.ReportToAgvs)
  SharedDtor();
}

void CamelMessage_ReportToAgvs::SharedDtor() {
  currentstation_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  version_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete posion_;
}

void CamelMessage_ReportToAgvs::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CamelMessage_ReportToAgvs& CamelMessage_ReportToAgvs::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CamelMessage_ReportToAgvs_camel_2dagvs_2dcommunication_2eproto.base);
  return *internal_default_instance();
}


void CamelMessage_ReportToAgvs::Clear() {
// @@protoc_insertion_point(message_clear_start:serialization.CamelMessage.ReportToAgvs)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  devices_.Clear();
  currentstation_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  version_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == nullptr && posion_ != nullptr) {
    delete posion_;
  }
  posion_ = nullptr;
  ::memset(&battery_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ischarging_) -
      reinterpret_cast<char*>(&battery_)) + sizeof(ischarging_));
  _internal_metadata_.Clear();
}

const char* CamelMessage_ReportToAgvs::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bytes currentStation = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_currentstation();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes version = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_version();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float battery = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          battery_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // bool isCharging = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          ischarging_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .serialization.Device devices = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_devices(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else goto handle_unusual;
        continue;
      // .serialization.Posion posion = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_posion(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CamelMessage_ReportToAgvs::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:serialization.CamelMessage.ReportToAgvs)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes currentStation = 1;
  if (this->currentstation().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_currentstation(), target);
  }

  // bytes version = 2;
  if (this->version().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_version(), target);
  }

  // float battery = 3;
  if (!(this->battery() <= 0 && this->battery() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_battery(), target);
  }

  // bool isCharging = 4;
  if (this->ischarging() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(4, this->_internal_ischarging(), target);
  }

  // repeated .serialization.Device devices = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_devices_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, this->_internal_devices(i), target, stream);
  }

  // .serialization.Posion posion = 6;
  if (this->has_posion()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        6, _Internal::posion(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:serialization.CamelMessage.ReportToAgvs)
  return target;
}

size_t CamelMessage_ReportToAgvs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:serialization.CamelMessage.ReportToAgvs)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .serialization.Device devices = 5;
  total_size += 1UL * this->_internal_devices_size();
  for (const auto& msg : this->devices_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // bytes currentStation = 1;
  if (this->currentstation().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_currentstation());
  }

  // bytes version = 2;
  if (this->version().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_version());
  }

  // .serialization.Posion posion = 6;
  if (this->has_posion()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *posion_);
  }

  // float battery = 3;
  if (!(this->battery() <= 0 && this->battery() >= 0)) {
    total_size += 1 + 4;
  }

  // bool isCharging = 4;
  if (this->ischarging() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CamelMessage_ReportToAgvs::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:serialization.CamelMessage.ReportToAgvs)
  GOOGLE_DCHECK_NE(&from, this);
  const CamelMessage_ReportToAgvs* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CamelMessage_ReportToAgvs>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:serialization.CamelMessage.ReportToAgvs)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:serialization.CamelMessage.ReportToAgvs)
    MergeFrom(*source);
  }
}

void CamelMessage_ReportToAgvs::MergeFrom(const CamelMessage_ReportToAgvs& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:serialization.CamelMessage.ReportToAgvs)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  devices_.MergeFrom(from.devices_);
  if (from.currentstation().size() > 0) {

    currentstation_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.currentstation_);
  }
  if (from.version().size() > 0) {

    version_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.version_);
  }
  if (from.has_posion()) {
    _internal_mutable_posion()->::serialization::Posion::MergeFrom(from._internal_posion());
  }
  if (!(from.battery() <= 0 && from.battery() >= 0)) {
    _internal_set_battery(from._internal_battery());
  }
  if (from.ischarging() != 0) {
    _internal_set_ischarging(from._internal_ischarging());
  }
}

void CamelMessage_ReportToAgvs::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:serialization.CamelMessage.ReportToAgvs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CamelMessage_ReportToAgvs::CopyFrom(const CamelMessage_ReportToAgvs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:serialization.CamelMessage.ReportToAgvs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CamelMessage_ReportToAgvs::IsInitialized() const {
  return true;
}

void CamelMessage_ReportToAgvs::InternalSwap(CamelMessage_ReportToAgvs* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  devices_.InternalSwap(&other->devices_);
  currentstation_.Swap(&other->currentstation_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  version_.Swap(&other->version_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(posion_, other->posion_);
  swap(battery_, other->battery_);
  swap(ischarging_, other->ischarging_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CamelMessage_ReportToAgvs::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void CamelMessage::InitAsDefaultInstance() {
  ::serialization::_CamelMessage_default_instance_.allowfromagvs_ = const_cast< ::serialization::CamelMessage_AllowFromAgvs*>(
      ::serialization::CamelMessage_AllowFromAgvs::internal_default_instance());
  ::serialization::_CamelMessage_default_instance_.reporttoagvs_ = const_cast< ::serialization::CamelMessage_ReportToAgvs*>(
      ::serialization::CamelMessage_ReportToAgvs::internal_default_instance());
}
class CamelMessage::_Internal {
 public:
  static const ::serialization::CamelMessage_AllowFromAgvs& allowfromagvs(const CamelMessage* msg);
  static const ::serialization::CamelMessage_ReportToAgvs& reporttoagvs(const CamelMessage* msg);
};

const ::serialization::CamelMessage_AllowFromAgvs&
CamelMessage::_Internal::allowfromagvs(const CamelMessage* msg) {
  return *msg->onlyone_.allowfromagvs_;
}
const ::serialization::CamelMessage_ReportToAgvs&
CamelMessage::_Internal::reporttoagvs(const CamelMessage* msg) {
  return *msg->onlyone_.reporttoagvs_;
}
void CamelMessage::set_allocated_allowfromagvs(::serialization::CamelMessage_AllowFromAgvs* allowfromagvs) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_onlyone();
  if (allowfromagvs) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      allowfromagvs = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, allowfromagvs, submessage_arena);
    }
    set_has_allowfromagvs();
    onlyone_.allowfromagvs_ = allowfromagvs;
  }
  // @@protoc_insertion_point(field_set_allocated:serialization.CamelMessage.allowFromAgvs)
}
void CamelMessage::set_allocated_reporttoagvs(::serialization::CamelMessage_ReportToAgvs* reporttoagvs) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_onlyone();
  if (reporttoagvs) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      reporttoagvs = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, reporttoagvs, submessage_arena);
    }
    set_has_reporttoagvs();
    onlyone_.reporttoagvs_ = reporttoagvs;
  }
  // @@protoc_insertion_point(field_set_allocated:serialization.CamelMessage.reportToAgvs)
}
CamelMessage::CamelMessage()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:serialization.CamelMessage)
}
CamelMessage::CamelMessage(const CamelMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clear_has_onlyone();
  switch (from.onlyone_case()) {
    case kAllowFromAgvs: {
      _internal_mutable_allowfromagvs()->::serialization::CamelMessage_AllowFromAgvs::MergeFrom(from._internal_allowfromagvs());
      break;
    }
    case kReportToAgvs: {
      _internal_mutable_reporttoagvs()->::serialization::CamelMessage_ReportToAgvs::MergeFrom(from._internal_reporttoagvs());
      break;
    }
    case ONLYONE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:serialization.CamelMessage)
}

void CamelMessage::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_CamelMessage_camel_2dagvs_2dcommunication_2eproto.base);
  clear_has_onlyone();
}

CamelMessage::~CamelMessage() {
  // @@protoc_insertion_point(destructor:serialization.CamelMessage)
  SharedDtor();
}

void CamelMessage::SharedDtor() {
  if (has_onlyone()) {
    clear_onlyone();
  }
}

void CamelMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CamelMessage& CamelMessage::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CamelMessage_camel_2dagvs_2dcommunication_2eproto.base);
  return *internal_default_instance();
}


void CamelMessage::clear_onlyone() {
// @@protoc_insertion_point(one_of_clear_start:serialization.CamelMessage)
  switch (onlyone_case()) {
    case kAllowFromAgvs: {
      delete onlyone_.allowfromagvs_;
      break;
    }
    case kReportToAgvs: {
      delete onlyone_.reporttoagvs_;
      break;
    }
    case ONLYONE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = ONLYONE_NOT_SET;
}


void CamelMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:serialization.CamelMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_onlyone();
  _internal_metadata_.Clear();
}

const char* CamelMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .serialization.CamelMessage.AllowFromAgvs allowFromAgvs = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_allowfromagvs(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .serialization.CamelMessage.ReportToAgvs reportToAgvs = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_reporttoagvs(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CamelMessage::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:serialization.CamelMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .serialization.CamelMessage.AllowFromAgvs allowFromAgvs = 1;
  if (_internal_has_allowfromagvs()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::allowfromagvs(this), target, stream);
  }

  // .serialization.CamelMessage.ReportToAgvs reportToAgvs = 2;
  if (_internal_has_reporttoagvs()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::reporttoagvs(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:serialization.CamelMessage)
  return target;
}

size_t CamelMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:serialization.CamelMessage)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (onlyone_case()) {
    // .serialization.CamelMessage.AllowFromAgvs allowFromAgvs = 1;
    case kAllowFromAgvs: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *onlyone_.allowfromagvs_);
      break;
    }
    // .serialization.CamelMessage.ReportToAgvs reportToAgvs = 2;
    case kReportToAgvs: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *onlyone_.reporttoagvs_);
      break;
    }
    case ONLYONE_NOT_SET: {
      break;
    }
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CamelMessage::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:serialization.CamelMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const CamelMessage* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CamelMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:serialization.CamelMessage)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:serialization.CamelMessage)
    MergeFrom(*source);
  }
}

void CamelMessage::MergeFrom(const CamelMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:serialization.CamelMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.onlyone_case()) {
    case kAllowFromAgvs: {
      _internal_mutable_allowfromagvs()->::serialization::CamelMessage_AllowFromAgvs::MergeFrom(from._internal_allowfromagvs());
      break;
    }
    case kReportToAgvs: {
      _internal_mutable_reporttoagvs()->::serialization::CamelMessage_ReportToAgvs::MergeFrom(from._internal_reporttoagvs());
      break;
    }
    case ONLYONE_NOT_SET: {
      break;
    }
  }
}

void CamelMessage::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:serialization.CamelMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CamelMessage::CopyFrom(const CamelMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:serialization.CamelMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CamelMessage::IsInitialized() const {
  return true;
}

void CamelMessage::InternalSwap(CamelMessage* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(onlyone_, other->onlyone_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata CamelMessage::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Posion::InitAsDefaultInstance() {
}
class Posion::_Internal {
 public:
};

Posion::Posion()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:serialization.Posion)
}
Posion::Posion(const Posion& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&theta_) -
    reinterpret_cast<char*>(&x_)) + sizeof(theta_));
  // @@protoc_insertion_point(copy_constructor:serialization.Posion)
}

void Posion::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&theta_) -
      reinterpret_cast<char*>(&x_)) + sizeof(theta_));
}

Posion::~Posion() {
  // @@protoc_insertion_point(destructor:serialization.Posion)
  SharedDtor();
}

void Posion::SharedDtor() {
}

void Posion::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Posion& Posion::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Posion_camel_2dagvs_2dcommunication_2eproto.base);
  return *internal_default_instance();
}


void Posion::Clear() {
// @@protoc_insertion_point(message_clear_start:serialization.Posion)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&theta_) -
      reinterpret_cast<char*>(&x_)) + sizeof(theta_));
  _internal_metadata_.Clear();
}

const char* Posion::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // float X = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float Y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float Theta = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          theta_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Posion::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:serialization.Posion)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float X = 1;
  if (!(this->x() <= 0 && this->x() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_x(), target);
  }

  // float Y = 2;
  if (!(this->y() <= 0 && this->y() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_y(), target);
  }

  // float Theta = 3;
  if (!(this->theta() <= 0 && this->theta() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_theta(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:serialization.Posion)
  return target;
}

size_t Posion::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:serialization.Posion)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float X = 1;
  if (!(this->x() <= 0 && this->x() >= 0)) {
    total_size += 1 + 4;
  }

  // float Y = 2;
  if (!(this->y() <= 0 && this->y() >= 0)) {
    total_size += 1 + 4;
  }

  // float Theta = 3;
  if (!(this->theta() <= 0 && this->theta() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Posion::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:serialization.Posion)
  GOOGLE_DCHECK_NE(&from, this);
  const Posion* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Posion>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:serialization.Posion)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:serialization.Posion)
    MergeFrom(*source);
  }
}

void Posion::MergeFrom(const Posion& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:serialization.Posion)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.x() <= 0 && from.x() >= 0)) {
    _internal_set_x(from._internal_x());
  }
  if (!(from.y() <= 0 && from.y() >= 0)) {
    _internal_set_y(from._internal_y());
  }
  if (!(from.theta() <= 0 && from.theta() >= 0)) {
    _internal_set_theta(from._internal_theta());
  }
}

void Posion::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:serialization.Posion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Posion::CopyFrom(const Posion& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:serialization.Posion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Posion::IsInitialized() const {
  return true;
}

void Posion::InternalSwap(Posion* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(theta_, other->theta_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Posion::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Device::InitAsDefaultInstance() {
}
class Device::_Internal {
 public:
};

Device::Device()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:serialization.Device)
}
Device::Device(const Device& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&value_) -
    reinterpret_cast<char*>(&id_)) + sizeof(value_));
  // @@protoc_insertion_point(copy_constructor:serialization.Device)
}

void Device::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Device_camel_2dagvs_2dcommunication_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value_) -
      reinterpret_cast<char*>(&id_)) + sizeof(value_));
}

Device::~Device() {
  // @@protoc_insertion_point(destructor:serialization.Device)
  SharedDtor();
}

void Device::SharedDtor() {
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Device::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Device& Device::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Device_camel_2dagvs_2dcommunication_2eproto.base);
  return *internal_default_instance();
}


void Device::Clear() {
// @@protoc_insertion_point(message_clear_start:serialization.Device)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value_) -
      reinterpret_cast<char*>(&id_)) + sizeof(value_));
  _internal_metadata_.Clear();
}

const char* Device::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool isActivate = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          isactivate_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float value = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37)) {
          value_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Device::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:serialization.Device)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // bytes name = 2;
  if (this->name().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_name(), target);
  }

  // bool isActivate = 3;
  if (this->isactivate() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_isactivate(), target);
  }

  // float value = 4;
  if (!(this->value() <= 0 && this->value() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(4, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:serialization.Device)
  return target;
}

size_t Device::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:serialization.Device)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_name());
  }

  // int32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_id());
  }

  // bool isActivate = 3;
  if (this->isactivate() != 0) {
    total_size += 1 + 1;
  }

  // float value = 4;
  if (!(this->value() <= 0 && this->value() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Device::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:serialization.Device)
  GOOGLE_DCHECK_NE(&from, this);
  const Device* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Device>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:serialization.Device)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:serialization.Device)
    MergeFrom(*source);
  }
}

void Device::MergeFrom(const Device& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:serialization.Device)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.id() != 0) {
    _internal_set_id(from._internal_id());
  }
  if (from.isactivate() != 0) {
    _internal_set_isactivate(from._internal_isactivate());
  }
  if (!(from.value() <= 0 && from.value() >= 0)) {
    _internal_set_value(from._internal_value());
  }
}

void Device::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:serialization.Device)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Device::CopyFrom(const Device& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:serialization.Device)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Device::IsInitialized() const {
  return true;
}

void Device::InternalSwap(Device* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(id_, other->id_);
  swap(isactivate_, other->isactivate_);
  swap(value_, other->value_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Device::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void AgvInAgvs::InitAsDefaultInstance() {
}
class AgvInAgvs::_Internal {
 public:
};

AgvInAgvs::AgvInAgvs()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:serialization.AgvInAgvs)
}
AgvInAgvs::AgvInAgvs(const AgvInAgvs& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  currentstation_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_currentstation().empty()) {
    currentstation_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.currentstation_);
  }
  targetstation_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_targetstation().empty()) {
    targetstation_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.targetstation_);
  }
  ::memcpy(&isuseable_, &from.isuseable_,
    static_cast<size_t>(reinterpret_cast<char*>(&hastask_) -
    reinterpret_cast<char*>(&isuseable_)) + sizeof(hastask_));
  // @@protoc_insertion_point(copy_constructor:serialization.AgvInAgvs)
}

void AgvInAgvs::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_AgvInAgvs_camel_2dagvs_2dcommunication_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  currentstation_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  targetstation_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&isuseable_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&hastask_) -
      reinterpret_cast<char*>(&isuseable_)) + sizeof(hastask_));
}

AgvInAgvs::~AgvInAgvs() {
  // @@protoc_insertion_point(destructor:serialization.AgvInAgvs)
  SharedDtor();
}

void AgvInAgvs::SharedDtor() {
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  currentstation_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  targetstation_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void AgvInAgvs::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const AgvInAgvs& AgvInAgvs::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_AgvInAgvs_camel_2dagvs_2dcommunication_2eproto.base);
  return *internal_default_instance();
}


void AgvInAgvs::Clear() {
// @@protoc_insertion_point(message_clear_start:serialization.AgvInAgvs)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  currentstation_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  targetstation_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&isuseable_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&hastask_) -
      reinterpret_cast<char*>(&isuseable_)) + sizeof(hastask_));
  _internal_metadata_.Clear();
}

const char* AgvInAgvs::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bytes name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes currentStation = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_currentstation();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes targetStation = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_targetstation();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool isUseable = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          isuseable_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool hasTask = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          hastask_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AgvInAgvs::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:serialization.AgvInAgvs)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes name = 1;
  if (this->name().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_name(), target);
  }

  // bytes currentStation = 2;
  if (this->currentstation().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_currentstation(), target);
  }

  // bytes targetStation = 3;
  if (this->targetstation().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_targetstation(), target);
  }

  // bool isUseable = 4;
  if (this->isuseable() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(4, this->_internal_isuseable(), target);
  }

  // bool hasTask = 5;
  if (this->hastask() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(5, this->_internal_hastask(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:serialization.AgvInAgvs)
  return target;
}

size_t AgvInAgvs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:serialization.AgvInAgvs)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_name());
  }

  // bytes currentStation = 2;
  if (this->currentstation().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_currentstation());
  }

  // bytes targetStation = 3;
  if (this->targetstation().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_targetstation());
  }

  // bool isUseable = 4;
  if (this->isuseable() != 0) {
    total_size += 1 + 1;
  }

  // bool hasTask = 5;
  if (this->hastask() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AgvInAgvs::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:serialization.AgvInAgvs)
  GOOGLE_DCHECK_NE(&from, this);
  const AgvInAgvs* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AgvInAgvs>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:serialization.AgvInAgvs)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:serialization.AgvInAgvs)
    MergeFrom(*source);
  }
}

void AgvInAgvs::MergeFrom(const AgvInAgvs& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:serialization.AgvInAgvs)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.currentstation().size() > 0) {

    currentstation_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.currentstation_);
  }
  if (from.targetstation().size() > 0) {

    targetstation_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.targetstation_);
  }
  if (from.isuseable() != 0) {
    _internal_set_isuseable(from._internal_isuseable());
  }
  if (from.hastask() != 0) {
    _internal_set_hastask(from._internal_hastask());
  }
}

void AgvInAgvs::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:serialization.AgvInAgvs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AgvInAgvs::CopyFrom(const AgvInAgvs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:serialization.AgvInAgvs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AgvInAgvs::IsInitialized() const {
  return true;
}

void AgvInAgvs::InternalSwap(AgvInAgvs* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  currentstation_.Swap(&other->currentstation_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  targetstation_.Swap(&other->targetstation_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(isuseable_, other->isuseable_);
  swap(hastask_, other->hastask_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AgvInAgvs::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace serialization
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::serialization::CamelMessage_AllowFromAgvs* Arena::CreateMaybeMessage< ::serialization::CamelMessage_AllowFromAgvs >(Arena* arena) {
  return Arena::CreateInternal< ::serialization::CamelMessage_AllowFromAgvs >(arena);
}
template<> PROTOBUF_NOINLINE ::serialization::CamelMessage_ReportToAgvs* Arena::CreateMaybeMessage< ::serialization::CamelMessage_ReportToAgvs >(Arena* arena) {
  return Arena::CreateInternal< ::serialization::CamelMessage_ReportToAgvs >(arena);
}
template<> PROTOBUF_NOINLINE ::serialization::CamelMessage* Arena::CreateMaybeMessage< ::serialization::CamelMessage >(Arena* arena) {
  return Arena::CreateInternal< ::serialization::CamelMessage >(arena);
}
template<> PROTOBUF_NOINLINE ::serialization::Posion* Arena::CreateMaybeMessage< ::serialization::Posion >(Arena* arena) {
  return Arena::CreateInternal< ::serialization::Posion >(arena);
}
template<> PROTOBUF_NOINLINE ::serialization::Device* Arena::CreateMaybeMessage< ::serialization::Device >(Arena* arena) {
  return Arena::CreateInternal< ::serialization::Device >(arena);
}
template<> PROTOBUF_NOINLINE ::serialization::AgvInAgvs* Arena::CreateMaybeMessage< ::serialization::AgvInAgvs >(Arena* arena) {
  return Arena::CreateInternal< ::serialization::AgvInAgvs >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
